#pragma once
#define TQ_ENGINE_PRESENTSURFACE "?PresentSurface@Engine@GAME@@QAEXXZ"
#define TQ_ENGINE_GENGINE "?gEngine@GAME@@3PAVEngine@1@A"
#define TQ_GAMEENGINE_GGAMEENGINE "?gGameEngine@GAME@@3PAVGameEngine@1@A"
#define TQ_ENGINE_HASLOADEDCUSTOMDATABASE "?HasLoadedCustomDatabase@Engine@GAME@@QAE_NXZ"
#define TQ_GAMEENGINE_GETMAINPLAYER "?GetMainPlayer@GameEngine@GAME@@QBEPAVPlayer@2@XZ"
#define TQ_ENGINE_GETGRAPHICSENGINE "?GetGraphicsEngine@Engine@GAME@@QBEPAVGraphicsEngine@2@XZ"
#define TQ_GFX_GETCANVAS "?GetCanvas@GraphicsEngine@GAME@@QAEAAVGraphicsCanvas@2@XZ"
#define TQ_GFX_CANVAS_GETWIDTH "?GetWidth@GraphicsCanvas@GAME@@QBEHXZ"
#define TQ_GFX_CANVAS_GETHEIGHT "?GetHeight@GraphicsCanvas@GAME@@QBEHXZ"
#define TQ_GFX_CANVAS_RENDERRECT "?RenderRect@GraphicsCanvas@GAME@@QAEXABVRect@2@ABVColor@2@PBVGraphicsShader2@2@ABVName@2@@Z"
#define TQ_GFX_CANVAS_RENDERTEXT_W "?RenderText@GraphicsCanvas@GAME@@QAEMHHABVColor@2@PBGPBVGraphicsFont@2@HW4XAlignment@12@W4YAlignment@12@_NHW4RenderFontStyle@2@5@Z"
#define TQ_GFX_LOADFONT "?LoadFont@GraphicsEngine@GAME@@QAEPBVGraphicsFont@2@ABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@_N1@Z"
#define TQ_INPUT_DISPLAY_HANDLEKEYEVENT "?HandleKeyEvent@Display@GAME@@QAEXABVButtonEvent@InputDevice@2@@Z"
